import {Platform, StyleSheet} from 'react-native';
import colors from './colors';
import {DimensionScreen} from '../config/constants';
const mainStyles = StyleSheet.create({
  content: {
    backgroundColor: '#ffffff',
    flex: 1,
  },
  container: {
    flex: 1,
    backgroundColor: '#f5f5f5',
  },
  cardShadow: {
    borderRadius: 8,
    shadowColor: colors.boxShadowColor,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  cardShadowPlus: {
    borderRadius: 8,
    shadowColor: colors.boxShadowColor,
    shadowOffset: {
      width: 0,
      height: 11,
    },
    shadowOpacity: 0.23,
    shadowRadius: 11.78,
    elevation: 15,
  },
  activityIndicator: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
  },
  activityIndicatorContainer: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: 'rgba(0,0,0,0.3)',
  },
  refreshButton: {
    backgroundColor: colors.refreshColor,
    padding: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 30,
    width: 210,
    borderRadius: 24,
  },
  saveSearch: {
    backgroundColor: colors.refreshColor,
    padding: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 16,
    width: 210,
    borderRadius: 24,
  },
  genericButton: {
    padding: 12,
    marginLeft: 5,
    marginRight: 5,
    justifyContent: 'center',
    alignItems: 'center',
    width: 210,
    borderRadius: 24,
  },
  textRefreshButton: {
    fontSize: 16,
    color: colors.white,
    fontWeight: '600',
  },
  text14: {
    fontSize: 14,
    color: colors.blackPro,
  },
  text14Red: {
    color: colors.red,
    fontSize: 14,
  },
  discreetText14: {
    color: colors.Dark_Grey,
    fontSize: 14,
    fontWeight: '600',
  },
  text16: {
    color: colors.blackPro,
    fontSize: 16,
  },
  text16Semi: {
    fontWeight: '700',
    fontSize: 16,
  },
  textUnderline16Semi: {
    fontSize: 16,
    alignItems: 'center',
    textAlign: 'center',
    color: colors.blackPro,
    fontWeight: '600',
    textDecorationLine: 'underline',
  },
  title20: {
    fontFamily: 'OpenSans-SemiBold',
    fontSize: 16,
    fontWeight: '600',
    color: colors.blackPro,
  },
  title19: {
    fontSize: 19,
    alignItems: 'center',
    textAlign: 'center',
    color: colors.blackPro,
    fontWeight: '500',
  },
  title19Bold: {
    fontSize: 19,
    alignItems: 'center',
    textAlign: 'center',
    color: colors.blackPro,
    fontWeight: 'bold',
  },
  titleUnderline19: {
    fontSize: 19,
    alignItems: 'center',
    textAlign: 'center',
    color: colors.blackPro,
    fontWeight: '500',
    textDecorationLine: 'underline',
  },
  titleUnderline19Bold: {
    fontSize: 19,
    alignItems: 'center',
    textAlign: 'center',
    color: colors.blackPro,
    fontWeight: 'bold',
    textDecorationLine: 'underline',
  },
  title22Bold: {
    color: colors.grey_dark,
    fontSize: 22,
    fontWeight: 'bold',
  },
  containerListComponent: {},
  listItem: {
    flexDirection: 'row',
    marginVertical: 6,
    width: 250,
  },
  bullet: {
    fontSize: 12,
    marginRight: 8,
    fontWeight: '600',
  },
  itemText: {
    fontSize: 13,
    fontWeight: '400',
    color: colors.blackPro,
  },
  containerTitleWithIcon: {
    justifyContent: 'space-between',
    flexDirection: 'row',
    alignItems: 'center',
    width: 255,
  },
  closeIcon: {
    alignItems: 'center',
    display: 'flex',
    justifyContent: 'center',
    marginTop: 1,
  },
  containerClose: {
    display: 'flex',
    justifyContent: 'center',
  },
  containerTitle: {
    alignItems: 'center',
    display: 'flex',
  },
  roundButtonStyleBlue: {
    backgroundColor: colors.lc_button_blue,
    height: 48,
    width: 286,
    flexDirection: 'row',
    // marginStart: 8,
    borderRadius: 24,
    paddingHorizontal: 10,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  horizontalView2: {
    flex: 1,
    flexDirection: 'row',
    alignSelf: 'center',
    alignContent: 'center',
    justifyContent: 'center',
  },
  text16MeduimWhite: {
    color: colors.white,
    fontSize: 16,
    fontWeight: '600',
  },
  searchBarStyle: {
    borderWidth: 1,
    borderColor: colors.grey_light,
    elevation: 0,
    borderRadius: 24,
    marginTop: 16,
    marginBottom: 5,
    marginHorizontal: 16,
  },
  roundedImageViewStyle: {
    backgroundColor: colors.lc_connect_blue,
    marginVertical: 12,
    marginHorizontal: 12,
    borderRadius: 8,
  },
  roundedViewStyle: {
    backgroundColor: colors.lc_connect_blue,
    marginVertical: 20,
    marginHorizontal: 20,
    borderRadius: 14,
  },
  roundedTranslucentViewStyle: {
    backgroundColor: colors.white,
    marginVertical: 20,
    marginHorizontal: 20,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.grey_super_light,
  },
  cellSimpleTextStyle: {
    marginLeft: 20,
    fontSize: 16,
    color: colors.grey1,
    fontFamily: 'OpenSans-SemiBold',
    fontWeight: 'normal',
  },
  modalContentWithoutCloseIcon: {
    //flex: 0.2,
    flexDirection: 'column',
    backgroundColor: 'white',
    borderRadius: 10,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContentWithCloseIcon: {
    flexDirection: 'column',
    backgroundColor: 'white',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: 12,
    paddingVertical: 2,
    borderRadius: 10,
    height: 308,
    width: 318,
  },
  modalText: {
    fontSize: 16,
    marginBottom: 10,
  },
  closeContainer: {
    padding: 10,
    alignSelf: 'flex-end',
  },
  closeButtonText: {
    color: colors.lc_blue,
    fontSize: 16,
    textDecorationLine: 'underline',
    fontWeight: '700',
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '700',
    justifyContent: 'center',
    alignItems: 'center',
    color: colors.titleColorModale,
  },
  confirmContainer: {
    justifyContent: 'center',
    backgroundColor: colors.confirmbutton,
    padding: 10,
    flex: 0.7,
    alignItems: 'center',
    borderRadius: 20,
    flexDirection: 'row',
    // height: 50,
  },
  titleConfirm: {
    color: colors.white,
    fontWeight: '700',
    fontSize: 16,
  },
  bodyModal: {
    fontWeight: '300',
    color: 'black',
    fontSize: 15,
    alignItems: 'center',
    textAlign: 'center',
  },
  containerEmptyResult: {
    justifyContent: 'center',
    alignItems: 'center',
    display: 'flex',
    flexDirection: 'column',
    flex: 1,
    height: DimensionScreen?.windowHeight * 0.7,
    backgroundColor: colors.white,
  },
  upperTextEmptyResult: {
    fontSize: 12,
    textAlign: 'left',
    color: colors.Dark_Grey,
    backgroundColor: colors.white,
    fontWeight: '400',
    fontStyle: 'italic',
    paddingVertical: 16,
    paddingHorizontal: 4,
    marginHorizontal: 8,
  },
  centerTextEmptyResult: {
    fontSize: 14,
    textAlign: 'center',
    color: colors.Dark_Grey,
    fontWeight: '600',
  },

  favoriteItemContainer: {
    //flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    margin: 33,
    backgroundColor: colors.white,
    borderRadius: 20,
    opacity: 3,
  },
  favoriteItemTitle: {
    color: 'black',
    flexDirection: 'row',
  },
  favoriteItemImage: {
    width: '100%', // Prend toute la largeur du parent
    height: '100%', // Prend toute la hauteur du parent
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  favoriteCircleIcon: {
    margin: 15,
  },
  textInfo: {
    fontSize: 14,
    color: 'black',
  },
  vehicleMake: {
    fontSize: 16,
    marginRight: 5,
    fontFamily: 'OpenSans-Regular',
    color: Platform.OS === 'android' && colors.blackPro,
    fontWeight: '700',
  },
  containerLoader: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  favoriteListStyle: {width: '100%'},
  actionSheetContainer: {
    backgroundColor: 'white',

    width: DimensionScreen.windowWidth,
    borderTopRightRadius: 20,
    borderTopLeftRadius: 20,
    flexDirection: 'column',
  },
  actionSheetContainerSearch: {
    backgroundColor: 'white',
    height:
      Platform.OS === 'android'
        ? DimensionScreen.windowHeight * 0.3
        : DimensionScreen.windowHeight * 0.3,
    width: DimensionScreen.windowWidth,
    // borderTopRightRadius: 54,
    // borderTopLeftRadius: 54,
    flexDirection: 'column',
  },
  actionSheetContainerLogin: {
    backgroundColor: 'white',
    height:
      Platform.OS === 'android'
        ? DimensionScreen.windowHeight * 0.31
        : DimensionScreen.windowHeight * 0.36,
    width: DimensionScreen.windowWidth,
    // borderTopRightRadius: 54,
    // borderTopLeftRadius: 54,
    flexDirection: 'column',
  },
  closeActionSheet: {margin: 0},
  containertSortModal: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 8,
    marginHorizontal: 8,
    justifyContent: 'space-between',
  },
  labelSortModalRadioButton: {
    fontSize: 14,
    fontWeight: '400',
    color: colors.blackPro,
  },
  mailTextStyle: {
    fontSize: 16,
    marginLeft: 15,
    marginVertical: 16,
    color: colors.black,
    fontFamily: 'OpenSans-Bold',
  },
  disconectTextStyle: {
    fontSize: 16,
    alignSelf: 'center',
    textDecorationLine: 'underline',
    color: colors.blackPro,
    fontFamily: 'OpenSans-Bold',
    fontWeight: 'normal',
  },
  animatedButtonFlatButton: {
    backgroundColor: colors.lc_button_blue,
    height: 48,
    borderRadius: 24,
    padding: 8,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  animatedButtonIconButton: {
    backgroundColor: colors.lc_button_blue,

    height: 48,
    borderRadius: 10,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  textAnimatedButton: {
    color: 'white',
    fontSize: 16,
    fontWeight: '600',
    marginLeft: 8,
  },
  toastSuccess: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'white',
    ...Platform.select({
      android: {
        elevation: 3,
        shadowColor: colors.boxShadowColor,
      },
      ios: {
        shadowColor: colors.boxShadowColor,
        shadowOffset: {width: 0, height: 3},
        shadowOpacity: 0.2,
        shadowRadius: 3,
      },
    }),
    justifyContent: 'center',
    height: 44,
    marginBottom: 52,
    borderRadius: 8,
  },
  toastText: {
    fontSize: 14,
    color: 'black',
    fontWeight: '400',
    textAlign: 'left',
  },
  version: {
    color: colors?.Dark_Grey,
    fontSize: 12,
    marginLeft: 20,
    marginTop: -8,
  },
  shadowAndroid: {
    borderBottomWidth: Platform?.OS === 'android' ? 1.5 : 0.5,
    borderBottomColor: colors?.grey3,
    backgroundColor: '#fff',
    shadowColor: '#000',
    shadowOffset: {width: 1, height: 1},
    shadowOpacity: Platform?.OS === 'android' ? 0.2 : 0,
    shadowRadius: Platform?.OS === 'android' ? 2 : 0,
    elevation: 3,
  },
});
export default mainStyles;
