schema:
  - http://localhost:8055/graphql
documents:
  - './App/**/*.graphql'
generates:
  ./src/generated/graphqlTypes.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
    presetConfig:
      extension: .generated.ts
      baseTypesPath: schemaTypes.ts
    config:
      withHooks: true
      withMutationFn: true
      withSubscriptions: true
